apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: foodflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: foodflux/delivery-service:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: orders_db
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password
            - name: KAFKA_BROKERS
              value: kafka:29092
            - name: PORT
              value: "3005"
          ports:
            - containerPort: 3005
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: foodflux
spec:
  selector:
    app: delivery-service
  ports:
    - port: 3005
      targetPort: 3005
  type: ClusterIP
